/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-variant': '#323537',
        'on-tertiary-fixed': '#131b2e',
        'on-secondary': '#480081',
        'on-tertiary-fixed-variant': '#3f465c',
        'on-primary-fixed-variant': '#004493',
        'on-error-container': '#ffdad6',
        'on-surface': '#e0e3e5',
        'tertiary': '#bec6e0',
        'surface-container': '#1d2022',
        'tertiary-fixed': '#dae2fd',
        'background': '#101415',
        'surface-container-highest': '#323537',
        'outline-variant': '#414754',
        'surface-bright': '#363a3b',
        'on-tertiary-container': '#22293d',
        'on-background': '#e0e3e5',
        'primary-container': '#4a8eff',
        'surface': '#101415',
        'secondary': '#dcb8ff',
        'surface-dim': '#101415',
        'on-secondary-fixed': '#2c0051',
        'inverse-surface': '#e0e3e5',
        'on-surface-variant': '#c1c6d7',
        'tertiary-container': '#8990a8',
        'on-secondary-container': '#dcb7ff',
        'surface-tint': '#adc7ff',
        'outline': '#8b90a0',
        'inverse-on-surface': '#2d3133',
        'surface-container-high': '#272a2c',
        'error-container': '#93000a',
        'primary': '#adc7ff',
        'secondary-fixed': '#efdbff',
        'on-primary': '#002e68',
        'surface-container-low': '#191c1e',
        'secondary-container': '#7701d0',
        'primary-fixed': '#d8e2ff',
        'on-primary-fixed': '#001a41',
        'inverse-primary': '#005bc0',
        'on-primary-container': '#00285b',
        'tertiary-fixed-dim': '#bec6e0',
        'error': '#ffb4ab',
        'surface-container-lowest': '#0b0f10',
        'on-tertiary': '#283044',
        'primary-fixed-dim': '#adc7ff',
        'on-secondary-fixed-variant': '#6700b5',
        'on-error': '#690005',
        'secondary-fixed-dim': '#dcb8ff',
      },
      spacing: {
        'stack-md': '16px',
        'container-max': '1440px',
        'margin-tablet': '32px',
        'stack-lg': '32px',
        'stack-xl': '64px',
        'margin-desktop': '64px',
        'stack-sm': '8px',
        'gutter': '32px',
        'stack-xs': '4px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      fontFamily: {
        'label-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'body-xl': ['Plus Jakarta Sans', 'sans-serif'],
        'display-xl': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'label-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'display-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-sm': ['30px', { lineHeight: '38px', fontWeight: '600' }],
        'body-xl': ['20px', { lineHeight: '32px', fontWeight: '400' }],
        'display-xl': ['72px', { lineHeight: '84px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg': ['60px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['36px', { lineHeight: '44px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
